"""Adiciona status preparo item pedido

Revision ID: 00047ff5a81a
Revises: ec32cdc84bae
Create Date: 2026-08-13 10:58:06.605011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00047ff5a81a'
down_revision = 'ec32cdc84bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_preparo', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_itens_pedido_status_preparo'), ['status_preparo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_status_preparo'))
        batch_op.drop_column('status_preparo')

    # ### end Alembic commands ###
