"""Adicionar fechamento e pagamento aos pedidos

Revision ID: 55646a4ba323
Revises: 9275a45cc0dc
Create Date: 2026-08-02 17:23:33.701626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55646a4ba323'
down_revision = '9275a45cc0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fechamento_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('fechamento_em')
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
