"""Criar tabela mesas

Revision ID: 5e9bee9db055
Revises: 00cb7c930a2f
Create Date: 2026-08-01 22:34:09.152672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9bee9db055'
down_revision = '00cb7c930a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mesas_numero'), ['numero'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mesas_numero'))

    op.drop_table('mesas')
    # ### end Alembic commands ###
