"""Cria fila de impressoes

Revision ID: 71b328443feb
Revises: 518ca49af41e
Create Date: 2026-08-11 19:43:00.782112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b328443feb'
down_revision = '518ca49af41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fila_impressoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('item_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('processado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fila_impressoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fila_impressoes_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_fila_impressoes_destino'), ['destino'], unique=False)
        batch_op.create_index(batch_op.f('ix_fila_impressoes_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fila_impressoes_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fila_impressoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fila_impressoes_status'))
        batch_op.drop_index(batch_op.f('ix_fila_impressoes_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_fila_impressoes_destino'))
        batch_op.drop_index(batch_op.f('ix_fila_impressoes_criado_em'))

    op.drop_table('fila_impressoes')
    # ### end Alembic commands ###
