"""Criar estrutura de pedidos

Revision ID: 9275a45cc0dc
Revises: bcd6f03b5923
Create Date: 2026-08-02 16:46:51.111786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9275a45cc0dc'
down_revision = 'bcd6f03b5923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_atendimento', sa.String(length=20), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('numero_marmitex', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('enviado_churrasqueira_em', sa.DateTime(), nullable=True),
    sa.Column('enviado_cozinha_em', sa.DateTime(), nullable=True),
    sa.Column('servido_em', sa.DateTime(), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_mesa_id'), ['mesa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_produto_id'), ['produto_id'], unique=False)

    op.create_table('itens_pedido_acompanhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['itens_pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido_acompanhamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_acompanhamentos_item_pedido_id'), ['item_pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_acompanhamentos_produto_id'), ['produto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido_acompanhamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_acompanhamentos_produto_id'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_acompanhamentos_item_pedido_id'))

    op.drop_table('itens_pedido_acompanhamentos')
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_produto_id'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_pedido_id'))

    op.drop_table('itens_pedido')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_status'))
        batch_op.drop_index(batch_op.f('ix_pedidos_mesa_id'))

    op.drop_table('pedidos')
    # ### end Alembic commands ###
