"""Adiciona nome cliente marmitex

Revision ID: ec32cdc84bae
Revises: 71b328443feb
Create Date: 2026-08-13 10:13:34.883752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec32cdc84bae'
down_revision = '71b328443feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_cliente', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_pedidos_nome_cliente'), ['nome_cliente'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_nome_cliente'))
        batch_op.drop_column('nome_cliente')

    # ### end Alembic commands ###
